name: Create Branch from Issue
on:
  project_card:
    types: [moved]

jobs:
  createBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create branch
        run: |
          if [[ "${{ github.event.project_card.column_id }}" == "8802897" ]]; then
            ISSUE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/projects/columns/cards/${{ github.event.project_card.id }} | jq .content_url | grep -o '[[:digit:]]\+')
            ISSUE_TITLE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_ID} | jq -r .title)
            BRANCH_NAME="${ISSUE_ID}-$(echo ${ISSUE_TITLE} | sed 's/ /-/g')"
            git checkout -b ${BRANCH_NAME}
            git push origin ${BRANCH_NAME}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
