name: Move issue on pull request close
on:
  pull_request:
    types: [closed]

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Move issue to done
      uses: alex-page/github-project-automation-plus@v0.6.0
      with:
        project: 'Money Tracker'
        column: 'Done'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
